# fly.toml app configuration file generated for ygg-rss-parser on 2023-10-30T10:10:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ygg-rss-parser"
primary_region = "cdg"

[build]
  build-target = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
