name: main
# Controls when the workflow will run
on:
  push:
    branches:
      - develop
  pull_request:

  workflow_dispatch:


jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8.10.0
    - uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: ESLint
      run: pnpm eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8.10.0
    - uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: Prettier
      run: pnpm prettier
