name: main
# Controls when the workflow will run
on:
  push:
    branches:
      - develop
  pull_request:

  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: ESLint
      run: pnpm eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: Prettier
      run: pnpm prettier
  
  depcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: Depcheck
      run: pnpm depcheck
  
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    needs: [eslint, prettier, depcheck]
    steps:
      - uses: actions/checkout@v4

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://${{secrets.DOKKU_HOST}}/appname'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
