name: main
# Controls when the workflow will run
on:
  push:
    branches:
      - develop
  pull_request:

  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: ESLint
      run: pnpm eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: Prettier
      run: pnpm prettier
  
  depcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: Depcheck
      run: pnpm depcheck
  
  deploy:
    name: Deploy app
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [eslint, prettier, depcheck]
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
